version: '3.8'
services:
  database:
    image: mariadb:10.5.17
    ports:
      - "3306:${MYSQL_PORT}"
    environment:
      - MYSQL_USER=vinylib
      - MYSQL_PASSWORD=vinylib
      - MYSQL_DATABASE=vinylib
      - MYSQL_ROOT_PASSWORD=vinylib
    volumes:
      - db_data:/lib/mysql/

  nginx:
    image: nginx
    volumes:
      - ./uploads:/usr/share/nginx/html
    ports:
      - "8081:80"

volumes:
  db_data:
