version: '3.8'
services:
  database:
    image: mariadb:10.5.17
    ports:
      - "3306:${MYSQL_PORT}"
    environment:
      - MYSQL_USER=vinylib
      - MYSQL_PASSWORD=vinylib
      - MYSQL_DATABASE=vinylib
      - MYSQL_ROOT_PASSWORD=vinylib
    volumes:
      - db_data:/lib/mysql/

volumes:
  db_data:
